; @@comment: the colon is the only thing that cannot be avoided in this approach
#lang org
; @@
# [[file:test.html]]
# [[file:test.pdf]]

#+latex_header: \usepackage{bigfoot}

#+keyword: hello

# (((( rainbow delims or my version of it is dumb

* plain lists
hello
1. There
   A. asdf

   B. asdf

2. 

wat
a) asdf
b) asdf


sigh
A) zz
B) qq


asdf
a. b
c. d
e. f

3. [@3] [X] wat :: some values
4. [ ]
5. [  ] more than one space does not work in the checkbox
6. [	] tab does not work in the checkbox
7. [X]
8. 


1. 
2. 
3. 
4. 

* drawers

                  :drawer:
yes this
is a drawer?
           :end:
more
                  :end:

:drawer:

:drawer-not-a-drawer:
| im a table | shor tand stout |
|            | lol             |
contents?!?
:end:

:end:
* [#D] qq


A. heloo
B. there

***nasdf
* tables
| i | am | a | table
| I | don't | need | to end in a pipe


| can you have newlines in cells?
  this seems strange to me? | no, you can't

* export snip
@@something: some words
and a newline too?
@@
Hrm
   
*this
is bold*

*test
a*

+this
should be
struck+

So the spec is inaccurate here. It is > 2 lines not > 3 lines. LESS than 3 lines is accurate.

~what
the code~

=what
the verbatim=

a *b* /c/ _d_ +e+ =f= ~g~ yes newline is a bug

* footnotes

Inline [fn::footnote] footnote.

Anchor [fn:x] footnote.

Inline anchor [fn:y:Because we are going to reference this somewhere else.] footnote.

Somewhere else [fn:y].

[fn:x] Definition

** here we go

Inline nested [fn::And now we have another footnote in here [fn::Nested.]]

Inline nested two [fn::
 asdf [fn::ech
 ]
 oof]

Inline nested three [fn::
 asdf [fn::ech
 ] this does not work
    #+begin_src bash
    echo seems like blocks can only go in non-inline footnotes
    #+end_src
 oof]

Inline drawer should fail [fn::
:hello:
this should not be an inline footnote I think?
:end:
] and thankfully is not.

Inline multiple spaces [fn::Paragraph thing


Hrm.


Sigh


] should still be part of the original paragraph?

HAHAH YES. IT IS NOT!
Despite the fact that the font locking regex shows that it is.

A [fn::B
C] D. Yes.

E [fn::F

G] H. No.

I [fn::J


K] L. No.

Wat [fn:q].

Intervening.

The following is NOT a footnote anchor [fn:con].
 [fn:con] confusingly.

Testing [fn:no-space].

What?!?!?!?! [fn:: [ hello =]= there
another p]

[fn:q] Hello there
#+begin_src bash
echo this works for html but not for pdf or latex? A regression I think?
echo no, you must have #+latex_header: \usepackage{bigfoot} for this
echo see https://tex.stackexchange.com/questions/203/how-to-obtain-verbatim-text-in-a-footnote
#+end_src
after block
:also:
a drawer!
:end:

[fn:con]

We have to have a real working =[fn:con]= definition otherwise org will not export.
You can't set =#+options: broken-footnotes:t= like you can with =#+options: broken-links:t=.

[fn:no-space]These don't require a space actually.

#+begin_src elisp
(+ 1 2)
#+end_src
